services:

  postgres:
    container_name: pg-database
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - main-network

  adminer:
    container_name: pg-adminer
    image: adminer
    restart: always
    ports:
      - 8078:8080
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  pgdata:
