services:

  postgres:
    container_name: pg-database
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - main-network

  # backend:
  #   container_name: backend
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   networks:
  #     - main-network

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #   networks:
  #     - main-network

networks:
  main-network:
    driver: bridge

volumes:
  pgdata:
