name: reviewdog
on: [pull_request]
jobs:
  ktlint:
    name: ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Run ktlint with reviewdog
        uses: ScaCap/action-ktlint@v1.9.0
        with:
          github_token: ${{ secrets.github_token }}
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tsc with reviewdog
        uses: EPMatt/reviewdog-action-tsc@v1.8.0
        with:
          github_token: ${{ secrets.github_token }}
          workdir: frontend
